### ISSUE TITLE
Sensibilidad al deslizar el dedo horizontalmente

### ISSUE THREAD

**Issue by JohnDoe25** [dan-zx/tedroid#17]
las piezas son muy sensibles al movimiento del dedo en la pantalla y se hace imprecisa la manipulacion

**Comment by alex9006** [comment]
estuve checando lo de la sensibilidad y a mi parecer con un MOVE_SENSITIVE= 6.5f  ya no pierdes control de la pieza cuando quieres moverla horizontalmente.

**Comment by dan-zx** [comment]
No lo mejora en el teléfono real
