### ISSUE TITLE
Game Over inválido

### ISSUE THREAD

**Issue by dan-zx** [dan-zx/tedroid#25]
Si hace una "torre" de piezas en un costado de la pantalla y se mueve inmediatamente la pieza que sigue a la cima de esa torre. Si la pieza no se puede mover más abajo se acaba el juego

**Comment by andres-pena-peralta** [comment]
![pruebas game over bloques predef](https://f.cloud.github.com/assets/6565946/2381727/2321d000-a8cb-11e3-9289-3e5ad1278467.png)

Creo que nos daba la impresión de que pasaba eso (game over inválido) porque la pieza que movíamos rápidamente no lográbamos quitarla completamente y  de todos modos quedaba obstruyendo a la siguiente pieza, lo que mandaba el game over

**Comment by andres-pena-peralta** [comment]
Ya no hay problema con las torres laterales. Si la nueva pieza puede acomodarse en la posición central inicial el juego puede continuar de lo contrario se activa el Game Over.

![game over 15 03](https://f.cloud.github.com/assets/6565946/2430045/63b88cde-acb4-11e3-8b2c-01b7e116799f.png)

**A pesar de haber una torre a la izquierda el juego continúa hasta que quiere aparecer la pieza roja que no puede acomodarse y por lo tanto finaliza el juego
